on:
    push:
        branches:
            - master
permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout repository
            - name: Prepare artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./landing/src
            - name: Deploy content
              id: deployment
              uses: actions/deploy-pages@v4
